# Generated by Django 4.1.1 on 2022-10-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoPais',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('codigo', models.TextField(blank=True, null=True)),
                ('anio', models.FloatField(blank=True, null=True)),
                ('petroleo', models.FloatField(blank=True, null=True)),
                ('carbon', models.FloatField(blank=True, null=True)),
                ('gas', models.FloatField(blank=True, null=True)),
                ('nuclear', models.FloatField(blank=True, null=True)),
                ('hidraulica', models.FloatField(blank=True, null=True)),
                ('solar', models.FloatField(blank=True, null=True)),
                ('eolica', models.FloatField(blank=True, null=True)),
                ('otras_renovables', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'consumo_pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmisionesContinente',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('continente', models.CharField(max_length=100)),
                ('n2019', models.FloatField(db_column='2019')),
                ('n2018', models.FloatField(db_column='2018')),
                ('n2017', models.FloatField(db_column='2017')),
                ('n2016', models.FloatField(db_column='2016')),
                ('n2015', models.FloatField(db_column='2015')),
                ('n2014', models.FloatField(db_column='2014')),
                ('n2013', models.FloatField(db_column='2013')),
                ('n2012', models.FloatField(db_column='2012')),
                ('n2011', models.FloatField(db_column='2011')),
                ('n2010', models.FloatField(db_column='2010')),
                ('n2009', models.FloatField(db_column='2009')),
                ('n2008', models.FloatField(db_column='2008')),
                ('n2007', models.FloatField(db_column='2007')),
                ('n2006', models.FloatField(db_column='2006')),
                ('n2005', models.FloatField(db_column='2005')),
                ('n2004', models.FloatField(db_column='2004')),
                ('n2003', models.FloatField(db_column='2003')),
                ('n2002', models.FloatField(db_column='2002')),
                ('n2001', models.FloatField(db_column='2001')),
                ('n2000', models.FloatField(db_column='2000')),
            ],
            options={
                'db_table': 'emisiones_continente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmisionesPais',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=100)),
                ('continente', models.CharField(max_length=100)),
                ('n2019', models.FloatField(blank=True, db_column='2019', null=True)),
                ('n2018', models.FloatField(blank=True, db_column='2018', null=True)),
                ('n2017', models.FloatField(blank=True, db_column='2017', null=True)),
                ('n2016', models.FloatField(blank=True, db_column='2016', null=True)),
                ('n2015', models.FloatField(blank=True, db_column='2015', null=True)),
                ('n2014', models.FloatField(blank=True, db_column='2014', null=True)),
                ('n2013', models.FloatField(blank=True, db_column='2013', null=True)),
                ('n2012', models.FloatField(blank=True, db_column='2012', null=True)),
                ('n2011', models.FloatField(blank=True, db_column='2011', null=True)),
                ('n2010', models.FloatField(blank=True, db_column='2010', null=True)),
                ('n2009', models.FloatField(blank=True, db_column='2009', null=True)),
                ('n2008', models.FloatField(blank=True, db_column='2008', null=True)),
                ('n2007', models.FloatField(blank=True, db_column='2007', null=True)),
                ('n2006', models.FloatField(blank=True, db_column='2006', null=True)),
                ('n2005', models.FloatField(blank=True, db_column='2005', null=True)),
                ('n2004', models.FloatField(blank=True, db_column='2004', null=True)),
                ('n2003', models.FloatField(blank=True, db_column='2003', null=True)),
                ('n2002', models.FloatField(blank=True, db_column='2002', null=True)),
                ('n2001', models.FloatField(blank=True, db_column='2001', null=True)),
                ('n2000', models.FloatField(blank=True, db_column='2000', null=True)),
            ],
            options={
                'db_table': 'emisiones_pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GasesMundial',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('N2O', models.FloatField(blank=True, db_column='N2O', null=True)),
                ('SF6', models.FloatField(blank=True, db_column='SF6', null=True)),
                ('CO2', models.FloatField(blank=True, db_column='CO2', null=True)),
                ('CH4', models.FloatField(blank=True, db_column='CH4', null=True)),
            ],
            options={
                'db_table': 'gases_mundial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HuellaMundial',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('biocapacidad', models.FloatField(blank=True, null=True)),
                ('huella_ecologica', models.FloatField(blank=True, null=True)),
                ('tierra', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'huella_mundial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HuellaPais',
            fields=[
                ('pais', models.TextField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('continente', models.TextField(blank=True, null=True)),
                ('indice_objetivos_desarrollo_sostenible', models.FloatField(blank=True, db_column='indice objetivos desarrollo sostenible', null=True)),
                ('expectativa_vida', models.FloatField(blank=True, db_column='expectativa vida', null=True)),
                ('indice_desarrollo_humano', models.FloatField(blank=True, db_column='indice desarrollo humano', null=True)),
                ('pib_per_capita', models.TextField(blank=True, db_column='pib per capita', null=True)),
                ('grupo_ingresos', models.TextField(blank=True, db_column='grupo ingresos', null=True)),
                ('poblacion', models.TextField(blank=True, null=True)),
                ('huella_carbono', models.FloatField(blank=True, db_column='huella carbono', null=True)),
                ('huella_ecologica', models.FloatField(blank=True, db_column='huella ecologica', null=True)),
                ('biocapacidad', models.FloatField(blank=True, null=True)),
                ('tierra', models.FloatField(blank=True, null=True)),
                ('idpais', models.TextField(blank=True, db_column='Idpais', null=True)),
                ('idcontinente', models.TextField(blank=True, db_column='Idcontinente', null=True)),
            ],
            options={
                'db_table': 'huella_pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InformacionPais',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('anio', models.FloatField(blank=True, null=True)),
                ('poblacion', models.FloatField(blank=True, null=True)),
                ('gen_elect', models.FloatField(blank=True, null=True)),
                ('dem_elect', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'informacion_pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MundialMaestro',
            fields=[
                ('anio', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('poblacion', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mundial_maestro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaisMaestro',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pais_maestro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrediccionMundial',
            fields=[
                ('anio', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('emision_co2', models.FloatField(blank=True, null=True)),
                ('produccion_energia', models.FloatField(blank=True, null=True)),
                ('var_emision_co2', models.FloatField(blank=True, null=True)),
                ('var_produccion_energia', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prediccion_mundial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProduccionPais',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('anio', models.FloatField(blank=True, null=True)),
                ('codigo', models.TextField(blank=True, null=True)),
                ('petroleo', models.FloatField(blank=True, null=True)),
                ('carbon', models.FloatField(blank=True, null=True)),
                ('gas', models.FloatField(blank=True, null=True)),
                ('nuclear', models.FloatField(blank=True, null=True)),
                ('hidraulica', models.FloatField(blank=True, null=True)),
                ('solar', models.FloatField(blank=True, null=True)),
                ('eolica', models.FloatField(blank=True, null=True)),
                ('otras_renovables', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'produccion_pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TemperaturaMundial',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('MAT', models.FloatField(blank=True, db_column='MAT', null=True)),
                ('lim_sup', models.FloatField(blank=True, null=True)),
                ('lim_inf', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'temperatura_mundial',
                'managed': False,
            },
        ),
    ]
